---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.0 include diverse nuove funzionalità e miglioramenti. 
---
= Novità di Cloud Volumes ONTAP 9.10.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.0 include diverse nuove funzionalità e miglioramenti.

Ulteriori funzionalità e miglioramenti sono stati introdotti anche nelle ultime versioni di BlueXP. Vedere https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Note di rilascio di BlueXP"^] per ulteriori informazioni.



== 9.10.0 GA (4 ottobre 2021)

La release GA 9.10.0 è disponibile in AWS, Azure e Google Cloud. Questa versione include le seguenti nuove funzioni e miglioramenti.



=== Miglioramento delle prestazioni di scrittura

Abbiamo migliorato le prestazioni di scrittura Cloud Volumes ONTAP quando è attivata l'alta velocità di scrittura.



=== Aumento delle dimensioni dei dischi NVRAM in Azure

La dimensione del disco NVRAM è stata aumentata da 128 GiB a 512 GiB per i nuovi sistemi Cloud Volumes ONTAP in Azure.


NOTE: Se si sceglie un sistema a nodo singolo e la macchina virtuale supporta SSD Ultra, il sistema utilizza un SSD Ultra da 32 GiB per NVRAM, invece di un SSD Premium da 512 GiB.



== Versione richiesta di BlueXP Connector

BlueXP Connector deve eseguire la versione 3.9.11 o successiva per implementare nuovi sistemi Cloud Volumes ONTAP 9.10.0 e aggiornare i sistemi esistenti alla versione 9.10.0.



== Note sull'aggiornamento

* Gli aggiornamenti di Cloud Volumes ONTAP devono essere completati da BlueXP. Non aggiornare Cloud Volumes ONTAP utilizzando Gestione di sistema o l'interfaccia CLI. In questo modo si può influire sulla stabilità del sistema.
* È possibile eseguire l'aggiornamento a Cloud Volumes ONTAP 9.10.0 dalla versione 9.9.1. BlueXP richiederà di aggiornare i sistemi Cloud Volumes ONTAP 9.9.1 esistenti alla versione 9.10.0.
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Scopri come eseguire l'aggiornamento quando BlueXP ti notifica"^].

* L'aggiornamento di un sistema a nodo singolo porta il sistema offline per un massimo di 25 minuti, durante i quali l'i/o viene interrotto.
* L'aggiornamento di una coppia ha è senza interruzioni e l'i/o è ininterrotto. Durante questo processo di aggiornamento senza interruzioni, ogni nodo viene aggiornato in tandem per continuare a fornire i/o ai client.
* In AWS, i tipi di istanze C4, M4 e R4 EC2 non sono più supportati con le nuove implementazioni di Cloud Volumes ONTAP. Se si dispone di un sistema in esecuzione su un tipo di istanza c4, m4 o r4, è necessario passare a un tipo di istanza nella famiglia di istanze c5, m5 o r5. Se non è possibile modificare il tipo di istanza, è necessario abilitare la rete avanzata prima di eseguire l'aggiornamento.
+
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Scopri come eseguire l'upgrade in AWS con i tipi di istanza C4, M4 e R4 EC2"^].
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Scopri come modificare il tipo di istanza EC2 per Cloud Volumes ONTAP"^].

+
Fare riferimento a. link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Supporto NetApp"^] per ulteriori informazioni sulla fine della disponibilità e sul supporto per questi tipi di istanze.





=== DS3_v2

A partire dalla versione 9.9.1, il tipo di macchina virtuale DS3_v2 non è più supportato dai sistemi Cloud Volumes ONTAP nuovi ed esistenti. Se si dispone di un sistema esistente in esecuzione su questo tipo di macchina virtuale, è necessario modificare i tipi di macchina virtuale prima di eseguire l'aggiornamento alla versione 9.10.0.
